### ISSUE TITLE
The number of hosts in the group name and showing the number of problems 

### ISSUE THREAD

**Issue by AlKosmos** [BGmot/zabbix-module-hosts-tree#2]
It would be good to have the number of  hosts in the group names and the number and the severity of issues showing:

Name of Group 1 (number of hosts in all groups down) (2 Problems)  
-> Name of group 2 (number of hosts in all groups down) (1 Problem) 
-> Name of Group 3 (number of hosts in Group 3)

Name of Group 1 (15) (2 Problems) 
-> Name of group 2 (10) (1 Problem) 
-> Name of Group 3 (5)

**Comment by BGmot** [comment]
Resolved by @miklert . Thanks!

**Comment by AlKosmos** [comment]
Thank you so much, it looks just fantastic now! We can see the number of hosts in the branch +  the severity and number of problem accordingly. So handy now.
