### ISSUE TITLE
A space between the group name and the host number in it

### ISSUE THREAD

**Issue by AlKosmos** [BGmot/zabbix-module-hosts-tree#4]
I think it would be more visual to  have a space between the group name and the host quantity in it. 

![image](https://user-images.githubusercontent.com/50465703/129741464-aaace7ab-600a-4237-af3d-db40682d1c73.png)

**Comment by BGmot** [comment]
Fixed by https://github.com/BGmot/zabbix-module-hosts-tree/commit/de3568f63d9d9dd3b8e92609a796206cbc744a47
