### ISSUE TITLE
Alphabetically arranged groups in the tree branches

### ISSUE THREAD

**Issue by AlKosmos** [BGmot/zabbix-module-hosts-tree#5]
I've just noticed, the groups in the tree branch are not arranged by alphabet. It would be a bit nicer to have them alphabetically organized.

**Comment by BGmot** [comment]
Resolved by https://github.com/BGmot/zabbix-module-hosts-tree/commit/2860cde7307915d0cbb8bfd6e5a3b21e7dea2173
