### ISSUE TITLE
Suggest to expand the list of hosts by default on the page or add a toggle switch

### ISSUE THREAD

**Issue by rollby** [BGmot/zabbix-module-hosts-tree#8]
Firstly, thank you for developing this zabbix module, I really like this feature.

However, when there are a large number of host devices, as this host list is collapsed and paged by default, it is easy to give a misunderstanding.

For example, I have several  parent host groups, referred to by code names A and B. When the host list is not expanded by default, once the page is switched, we will first see the name of the parent host  group displayed in the page, which can easily bring confusion as to why group B did not appear at the beginning and then appeared on the next page. Then click on the next page, and group A disappearsand.
![image](https://github.com/BGmot/zabbix-module-hosts-tree/assets/31183726/42d25d3a-9c8c-4876-a600-b71e9108d1cd)
![image](https://github.com/BGmot/zabbix-module-hosts-tree/assets/31183726/7fc00c46-f102-4b53-8a9e-bedb7b756a96)
![image](https://github.com/BGmot/zabbix-module-hosts-tree/assets/31183726/d698528b-5538-4ff9-b08f-2e2a7ebd8a91)

If we expand the list, we probably know that this is because the host list is paged, so why not expand by default at first or add a toggle switch, to avoid confusion.

**Comment by BGmot** [comment]
Implemented in https://github.com/BGmot/zabbix-module-hosts-tree/tree/v4.1.0

**Comment by rollby** [comment]
> Implemented in https://github.com/BGmot/zabbix-module-hosts-tree/tree/v4.1.0

Thanks a lot, but found some bugs.
If there are multi-level folders, when I click to collapse a folder, it can only hide up to two levels of its subfolders, and the folders  and hosts below cannot be hidden.
![image](https://github.com/BGmot/zabbix-module-hosts-tree/assets/31183726/2e68e917-e19f-4534-9f7f-7ef1d29f5af5)
![image](https://github.com/BGmot/zabbix-module-hosts-tree/assets/31183726/18eb64e4-10f1-4994-a4f9-71cbdcf811f7)

**Comment by rollby** [comment]
very thanks
